server:
  version: "0.0.1"
  project_name: "brainx"
  host: "0.0.0.0"
  port: 8000
  max_bytes: 10485760
  cors_origins:
    - "*"
  worker_count: 5
  environment: "local"
  server_render: False

jwt:
  jwt_secret: "dev"
  expire_in: 2592000 # 3600*24*30

api:
  api_prefix: "/api"
  openapi_prefix: "/openapi_provider"
  request_timeout: 60

openapi:
  Platforms:
    # 访问BrainX OpenAPI的restful 配置
    access_key: "key_brain_x"
    secret_key: "987654321"

  providers:
    # 访问PowerX OpenAPI的restful 配置
    - power_x:
        base_url: "http://127.0.0.1:8888/openapi/v1"
        secret_key: 'xxxxxxxxxxxx'

database:
  async_url: "postgresql+asyncpg://user:pass@127.0.0.1:54321/brain_x"
  sync_url: "postgresql://user:pass@127.0.0.1:54321/brain_x"
  table_name_vector_store: "embeddings"
  echo_log: False

cache:
  redis:
    url: redis://mypassword@localhost:6379/0
    use_jsonb: True

schedule:
  driver: apscheduler
  job_stores:
    default:
      type: sqlalchemy
      url: postgresql+psycopg2://username:password@localhost/dbname
  executors:
    default:
      type: threadpool
      max_workers: 10
  job_defaults:
    coalesce: false
    max_instances: 3

task:
  celery_broker_url: "redis://localhost:6379/0"
  celery_result_backend: "redis://localhost:6379/0"
  queue:
    default:
    rag_queue: rag_queue
  broker_use_ssl: False
  ssl_cert_reqs: ''
  ssl_ca_certs: ''
  ssl_cert_file: ''
  ssl_keyfile: ''
  result_expires: 3600
  broker_connection_retry_on_startup: True

models:
  qa_embedding_model_name: "shibing624/text2vec-base-chinese"
  visual_search_model_name: "clip-ViT-L-14"
  visual_query_model_name: "dandelin/vilt-b32-finetuned-vqa"

agent:
  framework_driver: langchain
  vdb: pgvector
  pgvector:
    url: "postgresql://user:pass@127.0.0.1:54321/brain_x"

log:
  path: logs
  split:
    - error
  level: info
  keep_days: 30
  console: True
  stat: False
  exc_info: False

test:
  db_url: 'postgresql+psycopg2://username:password@localhost/test_db'

openai:
  llm_name: "gpt-3.5-turbo"
  api_base: "https://api.openai.com/v1/"
  api_key: "YOUR_API_KEY"
  request_timeout: 30

baidu_qianfan:
  api_key: "YOUR_API_KEY"
  secret_key: "YOUR_SECRET_KEY"
  request_timeout: 30

ollama:
  url: "http://localhost:11434"

polygon:
  api_key: "YOUR_API_KEY"

sentry:
  dsn: "YOUR_DSN"
  environment: "local"
  release: "1.0"

storage:
  driver: "local"
  host: "127.0.0.1:8000"
  local_storage:
    storage_path: "./storage"
  minio:
    endpoint: "127.0.0.1:9001"
    access_key: "YOUR_ACCESS_KEY"
    secret_key: "YOUR_SECRET_KEY"
    use_ssl: True
    region: 'AsiaShanghai'
  aliyun:
    endpoint: "oss-cn-beijing.aliyuncs.com"
    access_key: "YOUR_ACCESS_KEY"
    secret_key: "YOUR_SECRET_KEY"
    bucket_name: "BUCKET_NAME"
  azure:
    account_name: 'ACCOUNT_NAME'
    account_key: 'ACCOUNT_KEY'
    container_name: 'CONTAINER_NAME'
    bucket_name: 'BUCKET_NAME'
  google:
    bucket_name: 'BUCKET_NAME'
  s3:
    endpoint: 'ENDPOINT'
    access_key: 'ACCESS_KEY'
    secret_key: 'SECRET_KEY'
    bucket_name: 'BUCKET_NAME'