server:
  version: "0.0.1"
  project_name: "brainx"
  host: "0.0.0.0"
  port: 8000
  max_bytes: 10485760
  cors_origins:
    - "*"
  worker_count: 5
  environment: "local"
  server_render: False

jwt:
  jwt_secret: "dev"
  expire_in: 2592000 # 3600*24*30

api:
  api_prefix: "/api"
  openapi_prefix: "/openapi"
  request_timeout: 60

openapi:
  access_key: "YOUR_ACCESS_KEY"
  secret_key: "YOUR_SECRET_KEY"

database:
  async_url: "postgresql+asyncpg://tenant:pass@127.0.0.1:54321/brain_x"
  sync_url: "postgresql://tenant:pass@127.0.0.1:54321/brain_x"
  table_name_vector_store: "embeddings"
  echo_log: False

cache:
  redis:
    url: redis://mypassword@localhost:6379/0

task:
  celery_broker_url: "redis://localhost:6379/0"
  celery_result_backend: "redis://localhost:6379/0"
  broker_use_ssl: False
  ssl_cert_reqs: ''
  ssl_ca_certs: ''
  ssl_cert_file: ''
  ssl_keyfile: ''
  result_expires: 3600
  broker_connection_retry_on_startup: True

models:
  qa_embedding_model_name: "shibing624/text2vec-base-chinese"
  visual_search_model_name: "clip-ViT-L-14"
  visual_query_model_name: "dandelin/vilt-b32-finetuned-vqa"

log:
  path: logs
  split:
    - error
  level: info
  keep_days: 30
  console: true
  stat: false

test:
  db_url: 'postgresql+psycopg2://username:password@localhost/test_db'

openai:
  llm_name: "gpt-3.5-turbo"
  api_base: "https://api.openai.com/v1/"
  api_key: "YOUR_API_KEY"
  request_timeout: 30

baidu_qianfan:
  api_key: "YOUR_API_KEY"
  secret_key: "YOUR_SECRET_KEY"
  request_timeout: 30

kimi:
  llm_name: "moonshot-v1-8k"
  api_key: "YOUR_API_KEY"
  api_base: "https://api.moonshot.cn/v1"
  request_timeout: 30

ollama:
  url: "http://localhost:11434"

polygon:
  api_key: "YOUR_API_KEY"

sentry:
  dsn: "YOUR_DSN"
  environment: "local"
  release: "1.0"

storage:
  driver: "local"
  host: "127.0.0.1:8000"
  local_storage:
    storage_path: "./storage"
  minio:
    endpoint: "127.0.0.1:9001"
    access_key: "YOUR_ACCESS_KEY"
    secret_key: "YOUR_SECRET_KEY"
    use_ssl: True
    region: 'AsiaShanghai'
  aliyun:
    endpoint: "oss-cn-beijing.aliyuncs.com"
    access_key: "YOUR_ACCESS_KEY"
    secret_key: "YOUR_SECRET_KEY"
    bucket_name: "BUCKET_NAME"
  azure:
    account_name: 'ACCOUNT_NAME'
    account_key: 'ACCOUNT_KEY'
    container_name: 'CONTAINER_NAME'
    bucket_name: 'BUCKET_NAME'
  google:
    bucket_name: 'BUCKET_NAME'
  s3:
    endpoint: 'ENDPOINT'
    access_key: 'ACCESS_KEY'
    secret_key: 'SECRET_KEY'
    bucket_name: 'BUCKET_NAME'