# 第一阶段：使用指定 Python 版本的 slim 镜像作为构建器
FROM python:3.12-slim AS builder

# 切换到 root 用户以进行安装
USER root

# 设置工作目录为 /app
WORKDIR /app


# 如果 /etc/apt/sources.list 不存在，则创建它
RUN touch /etc/apt/sources.list && \
    echo "deb http://deb.debian.org/debian bookworm main" > /etc/apt/sources.list && \
    echo "deb-src http://deb.debian.org/debian bookworm main" >> /etc/apt/sources.list

# 备份原有的源列表
RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak

# 使用阿里云的 Debian 源
RUN echo "deb http://mirrors.aliyun.com/debian/ bookworm main non-free non-free-firmware contrib" > /etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian/ bookworm main non-free non-free-firmware contrib" >> /etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian-security bookworm-security main" >> /etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian-security bookworm-security main" >> /etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian/ bookworm-updates main non-free non-free-firmware contrib" >> /etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian/ bookworm-updates main non-free non-free-firmware contrib" >> /etc/apt/sources.list

# 更新 apt 软件包列表并安装必要的依赖工具库
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    iputils-ping \
    make \
    gcc \
    g++ \
    python3-dev \
    libpq-dev \
    python3-tk || true && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*/var/lib/apt/lists/*

# 复制项目文件
COPY . /app/.

# 安装项目依赖项
# 使用 requirements.txt 文件来安装依赖
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# 运行 PyInstaller 来构建应用程序
RUN pyinstaller server.spec -y
RUN pyinstaller task.spec -y


# 执行下载脚本，确保 NLTK 数据被正确下载
RUN python /app/docker/scripts/download_nltk_data.py

# CMD ["tail", "-f", "/dev/null"]

# 第二阶段：使用指定 Python 版本的 slim 镜像作为运行环境
FROM python:3.12-slim AS runner


# 设置工作目录为 /app
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    iputils-ping \
    make \
    gcc \
    g++ \
    python3-dev \
    libpq-dev \
    python3-tk || true && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*/var/lib/apt/lists/*



# 重新安装 Python 项目的依赖
COPY --from=builder /app/requirements.txt /app/requirements.txt

#RUN pip install --upgrade pip && \
#    pip install --no-cache-dir -r requirements.txt

# 从构建器镜像中复制构建好的应用程序到当前镜像中
COPY --from=builder /app/dist /app/dist

# 复制配置文件和 Alembic 目录复制到当前镜像中
COPY --from=builder /app/alembic /app/alembic
COPY --from=builder /app/etc/alembic.example.ini /app/etc/alembic.ini
COPY --from=builder /app/server.spec /app/server.spec
COPY --from=builder /app/task.spec /app/task.spec

# 将项目脚本复制到 Docker 镜像中
COPY --from=builder /app/docker/ /app/docker/

# 赋予应用程序可执行权限
RUN chmod +x /app/dist/server/server
RUN chmod +x /app/docker/scripts/download_nltk_data.py
RUN chmod +x /app/docker/Makefile-build.mk





