# 第一阶段：使用指定 Python 版本的 slim 镜像作为构建器
FROM python:3.12-slim AS builder

# 切换到 root 用户以进行安装
USER root

# 设置工作目录为 /app
WORKDIR /app


# 如果 /etc/apt/sources.list 不存在，则创建它
RUN touch /etc/apt/sources.list && \
    echo "deb http://deb.debian.org/debian bookworm main" > /etc/apt/sources.list && \
    echo "deb-src http://deb.debian.org/debian bookworm main" >> /etc/apt/sources.list

# 备份原有的源列表
RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak

# 使用阿里云的 Debian 源
RUN echo "deb http://mirrors.aliyun.com/debian/ bookworm main non-free non-free-firmware contrib" > /etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian/ bookworm main non-free non-free-firmware contrib" >> /etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian-security bookworm-security main" >> /etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian-security bookworm-security main" >> /etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian/ bookworm-updates main non-free non-free-firmware contrib" >> /etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian/ bookworm-updates main non-free non-free-firmware contrib" >> /etc/apt/sources.list

# 更新 apt 软件包列表并安装必要的依赖工具库
RUN apt-get update && apt-get install -y gcc python3-dev libpq-dev python3-tk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# 安装 Poetry
# RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
RUN pip install poetry==1.8.2

COPY . /app/.
RUN echo "This is a test file" > tests.txt

# 安装项目依赖项
# 生成锁文件
RUN poetry lock --no-update
# 安装依赖
RUN poetry install --only main

# 运行 PyInstaller 来构建应用程序
# RUN poetry run pyinstaller server.py --clean -y
RUN poetry run pyinstaller server.spec -y
RUN poetry run pyinstaller task.spec -y

# CMD ["tail", "-f", "/dev/null"]

# 第二阶段：使用指定 Python 版本的 slim 镜像作为运行环境
FROM python:3.12-slim AS runner


# 设置工作目录为 /app
WORKDIR /app

# RUN apt-get update && apt-get install -y curl iputils-ping make
RUN apt-get update && \
    apt-get install -y curl iputils-ping make && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 重新安装 Python 项目的依赖
COPY --from=builder /app/pyproject.toml /app/poetry.lock /app/

RUN pip install poetry==1.8.2

RUN poetry install --no-dev

# 从构建器镜像中复制构建好的应用程序到当前镜像中
COPY --from=builder /app/dist /app/dist
# 复制配置文件和 Alembic 目录复制到当前镜像中
COPY --from=builder /app/alembic /app/alembic
COPY --from=builder /app/etc/alembic.example.ini /app/etc/alembic.ini
COPY --from=builder /app/server.spec /app/server.spec
COPY --from=builder /app/task.spec /app/task.spec
# 将项目脚本复制到 Docker 镜像中
COPY --from=builder /app/docker/scripts/download_nltk_data.py /app/scripts/download_nltk_data.py
COPY --from=builder /app/docker/Makefile /app/Makefile

# 赋予应用程序可执行权限
RUN chmod +x /app/dist/server/server
RUN chmod +x /app/scripts/download_nltk_data.py


# 设置代理服务器并安装 NLTK 及其依赖包
#RUN #pip install nltk && \
#    yes | python -m nltk.downloader \
#    -d /app/dist/server/_internal/llama_index/core/_static/nltk_cache \
#    stopwords punkt

# 安装 NLTK
RUN pip install nltk

# 执行下载脚本，确保 NLTK 数据被正确下载
RUN python /app/scripts/download_nltk_data.py

# 暴露应用程序使用的端口
EXPOSE 8000 

ENTRYPOINT ["poetry", "shell"]

# 定义容器启动时执行的默认命令
# CMD ["tail", "-f", "/dev/null"]
# CMD ["./dist/server/server"]
# CMD ["make", "-f", "/app/Makefile","-C", "/app", "app-init"]


